services:
  bin-it:
    image: ranasalem13/bin-it:latest
    container_name: bin-it
    environment:
      PYTHONUNBUFFERED: 1
      UPRN: ${UPRN}
      MONGO_URI: mongodb://mongodb:27017/
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      APP_PASSWORD: ${APP_PASSWORD}
      SENDER: ${SENDER}
      RECIPIENT: ${RECIPIENT}
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - '8080:8080'
    networks:
      - bin-it

  mongodb:
    image: mongo:latest
    container_name: bin-it-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data
    networks:
      - bin-it

  mongo-express:
    image: mongo-express:latest
    container_name: bin-it-mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      mongodb:
        condition: service_started
    ports:
      - '8081:8081'
    networks:
      - bin-it

volumes:
  mongodb-data:

networks:
  bin-it:
    driver: bridge
    name: bin-it
