services:
  ollama:
    image: ollama/ollama:latest
    container_name: homelab-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - homelab-net

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.9.5
    container_name: homelab-open-webui
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "3006:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=some-random-string
      - WEBUI_NAME=Rana's Homelab
      - WEBUI_HOST=0.0.0.0
      - CORS_ALLOW_ORIGIN=*
      - RAG_EMBEDDING_MODEL=""
      - ENABLE_RAG_WEB_SEARCH=false
    healthcheck:
      disable: true
    volumes:
      - open-webui:/app/backend/data
    networks:
      - homelab-net

volumes:
  ollama:
  open-webui:

networks:
  homelab-net:
    driver: bridge
    name: homelab-net
