services:
  wireguard:
    image: linuxserver/wireguard
    container_name: homelab-wireguard
    restart: unless-stopped
    ports:
      - 3003:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SERVERURL: ${SERVERURL}
      SERVERPORT: ${SERVERPORT}
      PEERS: ${PEERS}
      PEERDNS: ${PEERDNS}        
      INTERNAL_SUBNET: ${INTERNAL_SUBNET}
    volumes:
      - wireguard_config:/config
      - /lib/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - homelab-net

volumes:
  wireguard_config:
    
networks:
  homelab-net:
    driver: bridge
    name: homelab-net
