services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: homelab-ntfy
    restart: unless-stopped
    command:
      - serve
    ports:
      - 3005:80
    environment:
      - TZ=UTC
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-config:/etc/ntfy
    networks:
      - homelab-net

volumes:
  ntfy-cache:
  ntfy-config:

networks:
  homelab-net:
    driver: bridge
    name: homelab-net
