services:
  adminer:
    image: adminer:latest
    container_name: homelab-db
    restart: always
    ports:
      - 3003:8080
    networks:
      -  homelab-net

networks:
  homelab-net:
    driver: bridge
    name: homelab-net
