services:
  grafana:
    image: grafana/grafana:latest
    container_name: homelab-grafana
    restart: unless-stopped
    ports:
      - 3001:3000
    networks:
    - homelab-net

networks:
  homelab-net:
    driver: bridge
    name: homelab-net
