services:
  mediawiki:
    image: mediawiki:stable
    container_name: homelab-mediawiki
    restart: always
    ports:
      - 3005:80
    networks:
      - homelab-net

  mariadb:
    image: mariadb:latest
    container_name: homelab-wiki-db
    restart: always
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - homelab-net

volumes:
  db_data:

networks:
  homelab-net:
    driver: bridge
    name: homelab-net
