services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: homelab-ntfy
    restart: unless-stopped
    command:
      - serve
    ports:
      - 80:80
    environment:
      - TZ=UTC
    volumes:
      - ntfy-cache:/var/cache/ntfy
      - ntfy-config:/etc/ntfy

volumes:
  ntfy-cache:
  ntfy-config:
