#!/bin/bash

set -e

cd "$(dirname "$0")"

show_services() {
  echo
  echo "Available services:"
  echo
  echo "bin-it"
  echo "cloudflared"
  echo "navidrome"
  echo "ntfy"
  echo "ollama"
  echo "portainer"
  echo "vaultwarden"
  echo "all"
  echo
  echo "Usage examples:"
  echo "./start cloudflared"
  echo "./start cloudflared portainer"
  echo "./start all"
  echo "./start all --ai    (includes Ollama)"
}

FILES=()
AI=false

for arg in "$@"; do
  case "$arg" in
  bin-it)
    FILES+=("-f" "compose.bin-it.yaml")
    ;;
  cloudflared)
    FILES+=("-f" "compose.cloudflared.yaml")
    ;;
  navidrome)
    FILES+=("-f" "compose.navidrome.yaml")
    ;;
  ntfy)
    FILES+=("-f" "compose.ntfy.yaml")
    ;;
  ollama)
    FILES+=("-f" "compose.ollama.yaml")
    ;;
  portainer)
    FILES+=("-f" "compose.portainer.yaml")
    ;;
  vaultwarden)
    FILES+=("-f" "compose.vaultwarden.yaml")
    ;;
  all)
    FILES+=("-f" "compose.bin-it.yaml" "-f" "compose.cloudflared.yaml" "-f" "compose.navidrome.yaml" "-f" "compose.ntfy.yaml" "-f" "compose.portainer.yaml" "-f" "compose.vaultwarden.yaml")
    ;;
  --ai)
    AI=true
    ;;
  *)
    echo "$arg is an unknown service"
    show_services
    exit 1
    ;;
  esac
done

if [ "$AI" = true ]; then
  FILES+=("-f" "compose.ollama.yaml")
fi

if [ ${#FILES[@]} -eq 0 ]; then
  echo "Error: no services specified"
  show_services
  exit 1
fi

if ! docker compose "${FILES[@]}" up -d; then
  echo "Error occurred while starting services"
  exit 1
fi
