#!/bin/bash

set -e

cd "$(dirname "$0")"

show_services() {
  echo
  echo "Available services:"
  echo
  echo "| Service     | Argument  |"
  echo "|-------------|-----------|"
  echo "| portainer   | prt       |"
  echo "| grafana     | gfn       |"
  echo "| cloudflared | cfd       |"
  echo "| all         | all       |"
  echo
  echo "Usage examples:"
  echo "./start prt"
  echo "./start prt gfn"
  echo "./start all"
}

FILES=()

for arg in "$@"; do
  case "$arg" in
  prt)
    FILES+=("-f" "compose.portainer.yaml")
    ;;
  gfn)
    FILES+=("-f" "compose.grafana.yaml")
    ;;
  cfd)
    FILES+=("-f" "compose.cloudflared.yaml")
    ;;
  all)
    FILES+=("-f" "compose.portainer.yaml" "-f" "compose.grafana.yaml" "-f" "compose.cloudflared.yaml")
    ;;
  *)
    echo "$arg is an unknown service"
    show_services
    exit 1
    ;;
  esac
done

if [ ${#FILES[@]} -eq 0 ]; then
  echo "Error: no services specified"
  show_services
  exit 1
fi

if ! docker compose "${FILES[@]}" down; then
  echo "Error occurred while bringing up services"
  exit 1
fi
